server:
  port: 80

zuul:
  routes:
    auth-server:
      path: /login/**
      url: http://127.0.0.1:8081/
      sensitiveHeaders: Cookie,Set-Cookie
      stripPrefix: false
    product:
      path: /product/**
      url: http://127.0.0.1:9001/
      stripPrefix: false
    order:
      path: /order/**
      url: http://127.0.0.1:9002/
      stripPrefix: false
      sensitiveHeaders: Cookie,Set-Cookie
    search:
      path: /search/**
      url: http://127.0.0.1:9200/
      prefix: /search/
      stripPrefix: true


com.koehler.security.jwt.secret: pocecommercedropshipping

spring:
  application:
    name: api-gateway

  sleuth:
    sampler:
      probability: 1

  zipkin:
    base-url: http://localhost:9411/